volumes:
  n8n_storage:
  ollama_storage:
  qdrant_storage:

networks:
  network:

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-local
    restart: unless-stopped
    networks:
      - network
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${N8N_POSTGRES_HOST}
      - DB_POSTGRESDB_USER=${N8N_POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${N8N_POSTGRES_PASSWORD}
      - N8N_ENCRYPTION_KEY=super-secret-key
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./n8n/docs:/home/node/docs

  nginx:
    image: nginx:latest
    container_name: nginx-local
    restart: unless-stopped
    networks:
      - network
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certificates:/etc/nginx/certificates
    depends_on:
      - n8n

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-local
    restart: unless-stopped
    networks:
      - network
    ports:
      - 11434:11434
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ollama_storage:/root/.ollama

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant-local
    networks: 
      - network
    restart: unless-stopped
    ports:
      - 6333:6333
    volumes:
      - qdrant_storage:/qdrant/storage
