volumes:
  n8n_storage:
  ollama_storage:

networks:
  network:

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-local
    restart: unless-stopped
    networks:
      - network
    ports:
      - 5678:5678
    environment:
      - DB_TYPE=sqlite
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_ENCRYPTION_KEY=<your-encryption-key>
      - N8N_USER_MANAGEMENT_JWT_SECRET=<your-jwt-secret>
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_storage:/home/node/.n8n
  
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-local
    restart: unless-stopped
    networks:
      - network
    ports:
      - 11434:11434
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ollama_storage:/root/.ollama
